# Generated by Django 5.0.1 on 2024-01-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_songbook_songbookentry_songbook_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time_signature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
