# Generated by Django 5.0.1 on 2024-01-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_song_time_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
